[2022-09-17 02:26:51,142] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T02:24:23.333677+00:00 [queued]>
[2022-09-17 02:26:51,237] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T02:24:23.333677+00:00 [queued]>
[2022-09-17 02:26:51,239] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 02:26:51,241] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-09-17 02:26:51,243] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 02:26:51,306] {taskinstance.py:1038} INFO - Executing <Task(BigQueryCheckOperator): check_query_big_query_table> on 2022-09-17T02:24:23.333677+00:00
[2022-09-17 02:26:51,367] {standard_task_runner.py:51} INFO - Started process 1917 to run task
[2022-09-17 02:26:51,417] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery_dag', 'check_query_big_query_table', '2022-09-17T02:24:23.333677+00:00', '--job-id', '221', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bigquery.py', '--cfg-path', '/tmp/tmp75jg46si']
[2022-09-17 02:26:51,430] {standard_task_runner.py:76} INFO - Job 221: Subtask check_query_big_query_table
[2022-09-17 02:26:51,571] {logging_mixin.py:103} INFO - Running <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T02:24:23.333677+00:00 [running]> on host 27377494ab8b
[2022-09-17 02:26:51,747] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=bigquery_dag
AIRFLOW_CTX_TASK_ID=check_query_big_query_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-17T02:24:23.333677+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-17T02:24:23.333677+00:00
[2022-09-17 02:26:51,757] {sql.py:87} INFO - Executing SQL check: 
           select id from githubarchive.day.20220914
        
[2022-09-17 02:26:51,814] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:120 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2022-09-17 02:26:51,818] {taskinstance.py:1396} ERROR - [Errno 2] No such file or directory: '/opt/airflow/dags/support/keys/quick-keel-213611-bfc0c6523d4e.json'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/sql.py", line 88, in execute
    records = self.get_db_hook().get_first(self.sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 147, in get_first
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 107, in get_conn
    service = self.get_service()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 122, in get_service
    http_authorized = self._authorize()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 280, in _authorize
    credentials = self._get_credentials()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 251, in _get_credentials
    credentials, _ = self._get_credentials_and_project_id()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 237, in _get_credentials_and_project_id
    delegates=delegates,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 309, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 238, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 286, in _get_credentials_using_key_path
    self.key_path, scopes=self.scopes
  File "/home/airflow/.local/lib/python3.6/site-packages/google/oauth2/service_account.py", line 234, in from_service_account_file
    filename, require=["client_email", "token_uri"]
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_service_account_info.py", line 72, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/support/keys/quick-keel-213611-bfc0c6523d4e.json'
[2022-09-17 02:26:51,836] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=bigquery_dag, task_id=check_query_big_query_table, execution_date=20220917T022423, start_date=20220917T022651, end_date=20220917T022651
[2022-09-17 02:26:51,940] {local_task_job.py:118} INFO - Task exited with return code 1
