[2022-09-17 02:26:50,231] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-17 02:26:50,290] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-17 02:26:50,302] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 02:26:50,304] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-09-17 02:26:50,307] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 02:26:50,475] {taskinstance.py:1038} INFO - Executing <Task(BigQueryCheckOperator): check_query_big_query_table> on 2022-09-10T03:00:00+00:00
[2022-09-17 02:26:50,517] {standard_task_runner.py:51} INFO - Started process 1915 to run task
[2022-09-17 02:26:50,579] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery_dag', 'check_query_big_query_table', '2022-09-10T03:00:00+00:00', '--job-id', '220', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bigquery.py', '--cfg-path', '/tmp/tmp22jc6cbf']
[2022-09-17 02:26:50,617] {standard_task_runner.py:76} INFO - Job 220: Subtask check_query_big_query_table
[2022-09-17 02:26:51,027] {logging_mixin.py:103} INFO - Running <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-17 02:26:51,235] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=bigquery_dag
AIRFLOW_CTX_TASK_ID=check_query_big_query_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T03:00:00+00:00
[2022-09-17 02:26:51,252] {sql.py:87} INFO - Executing SQL check: 
           select id from githubarchive.day.20220914
        
[2022-09-17 02:26:51,397] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:120 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2022-09-17 02:26:51,407] {taskinstance.py:1396} ERROR - [Errno 2] No such file or directory: '/opt/airflow/dags/support/keys/quick-keel-213611-bfc0c6523d4e.json'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/sql.py", line 88, in execute
    records = self.get_db_hook().get_first(self.sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 147, in get_first
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 107, in get_conn
    service = self.get_service()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 122, in get_service
    http_authorized = self._authorize()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 280, in _authorize
    credentials = self._get_credentials()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 251, in _get_credentials
    credentials, _ = self._get_credentials_and_project_id()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 237, in _get_credentials_and_project_id
    delegates=delegates,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 309, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 238, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 286, in _get_credentials_using_key_path
    self.key_path, scopes=self.scopes
  File "/home/airflow/.local/lib/python3.6/site-packages/google/oauth2/service_account.py", line 234, in from_service_account_file
    filename, require=["client_email", "token_uri"]
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_service_account_info.py", line 72, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/support/keys/quick-keel-213611-bfc0c6523d4e.json'
[2022-09-17 02:26:51,437] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=bigquery_dag, task_id=check_query_big_query_table, execution_date=20220910T030000, start_date=20220917T022650, end_date=20220917T022651
[2022-09-17 02:26:51,529] {local_task_job.py:118} INFO - Task exited with return code 1
[2022-09-18 18:31:44,528] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-18 18:31:44,747] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-18 18:31:44,758] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 18:31:44,761] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-09-18 18:31:44,766] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 18:31:44,912] {taskinstance.py:1038} INFO - Executing <Task(BigQueryCheckOperator): check_query_big_query_table> on 2022-09-10T03:00:00+00:00
[2022-09-18 18:31:44,967] {standard_task_runner.py:51} INFO - Started process 1568 to run task
[2022-09-18 18:31:45,003] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery_dag', 'check_query_big_query_table', '2022-09-10T03:00:00+00:00', '--job-id', '277', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bigquery.py', '--cfg-path', '/tmp/tmp8dkb9f0f']
[2022-09-18 18:31:45,047] {standard_task_runner.py:76} INFO - Job 277: Subtask check_query_big_query_table
[2022-09-18 18:31:45,610] {logging_mixin.py:103} INFO - Running <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-18 18:31:46,773] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=bigquery_dag
AIRFLOW_CTX_TASK_ID=check_query_big_query_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T03:00:00+00:00
[2022-09-18 18:31:46,834] {sql.py:87} INFO - Executing SQL check: 
           select id from githubarchive.day.20220914
        
[2022-09-18 18:31:47,066] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:120 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2022-09-18 18:31:49,250] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:2052 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2022-09-18 18:31:49,266] {bigquery.py:1510} INFO - Inserting job airflow_1663525909264096_06d2bf8b43be9b79a3e89edf3b53e367
[2022-09-18 18:31:50,924] {local_task_job.py:170} WARNING - State of this instance has been externally set to None. Terminating instance.
[2022-09-18 18:31:51,019] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 1568
[2022-09-18 18:31:51,034] {taskinstance.py:1214} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-09-18 18:31:51,144] {taskinstance.py:1396} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/sql.py", line 88, in execute
    records = self.get_db_hook().get_first(self.sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 152, in get_first
    cur.execute(sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2639, in execute
    self.job_id = self.hook.run_query(sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2186, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1512, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1159, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/base.py", line 628, in result
    self._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1069, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/base.py", line 438, in _begin
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 640, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/_http.py", line 479, in api_request
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/_http.py", line 337, in _make_request
    method, url, headers, data, target_object, timeout=timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/_http.py", line 375, in _do_request
    url=url, method=method, headers=headers, data=data, timeout=timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/transport/requests.py", line 487, in request
    **kwargs
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1383, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1839, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1216, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-09-18 18:31:51,231] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=bigquery_dag, task_id=check_query_big_query_table, execution_date=20220910T030000, start_date=20220918T183144, end_date=20220918T183151
[2022-09-18 18:31:51,528] {process_utils.py:61} INFO - Process psutil.Process(pid=1568, status='terminated', exitcode=1, started='18:31:44') (1568) terminated with exit code 1
[2022-09-18 18:31:51,539] {local_task_job.py:118} INFO - Task exited with return code 1
[2022-09-18 18:40:47,466] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-18 18:40:47,599] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-18 18:40:47,601] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 18:40:47,603] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-09-18 18:40:47,610] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 18:40:47,711] {taskinstance.py:1038} INFO - Executing <Task(BigQueryCheckOperator): check_query_big_query_table> on 2022-09-10T03:00:00+00:00
[2022-09-18 18:40:47,775] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery_dag', 'check_query_big_query_table', '2022-09-10T03:00:00+00:00', '--job-id', '315', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bigquery.py', '--cfg-path', '/tmp/tmpdbga30r_']
[2022-09-18 18:40:47,785] {standard_task_runner.py:76} INFO - Job 315: Subtask check_query_big_query_table
[2022-09-18 18:40:47,747] {standard_task_runner.py:51} INFO - Started process 1549 to run task
[2022-09-18 18:40:48,326] {logging_mixin.py:103} INFO - Running <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-18 18:40:48,736] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=bigquery_dag
AIRFLOW_CTX_TASK_ID=check_query_big_query_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T03:00:00+00:00
[2022-09-18 18:40:48,794] {sql.py:87} INFO - Executing SQL check: 
           select id from githubarchive.day.20220914
        
[2022-09-18 18:40:49,113] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:120 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2022-09-18 18:40:51,430] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:2052 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2022-09-18 18:40:51,439] {bigquery.py:1510} INFO - Inserting job airflow_1663526451435592_06d2bf8b43be9b79a3e89edf3b53e367
[2022-09-18 18:41:19,598] {local_task_job.py:118} INFO - Task exited with return code Negsignal.SIGKILL
[2022-09-18 19:18:34,430] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-18 19:18:34,513] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-18 19:18:34,516] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 19:18:34,517] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-09-18 19:18:34,518] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 19:18:34,577] {taskinstance.py:1038} INFO - Executing <Task(BigQueryCheckOperator): check_query_big_query_table> on 2022-09-10T03:00:00+00:00
[2022-09-18 19:18:34,588] {standard_task_runner.py:51} INFO - Started process 3995 to run task
[2022-09-18 19:18:34,631] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery_dag', 'check_query_big_query_table', '2022-09-10T03:00:00+00:00', '--job-id', '368', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bigquery.py', '--cfg-path', '/tmp/tmptrl5a34x']
[2022-09-18 19:18:34,647] {standard_task_runner.py:76} INFO - Job 368: Subtask check_query_big_query_table
[2022-09-18 19:18:34,828] {logging_mixin.py:103} INFO - Running <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-18 19:18:34,979] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=bigquery_dag
AIRFLOW_CTX_TASK_ID=check_query_big_query_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T03:00:00+00:00
[2022-09-18 19:18:34,991] {sql.py:87} INFO - Executing SQL check: 
           select id from githubarchive.day.20220914
        
[2022-09-18 19:18:35,057] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:120 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2022-09-18 19:18:35,964] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:2052 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2022-09-18 19:18:35,971] {bigquery.py:1510} INFO - Inserting job airflow_1663528715967019_06d2bf8b43be9b79a3e89edf3b53e367
[2022-09-18 19:18:36,445] {taskinstance.py:1396} ERROR - 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/quick-keel-213611/jobs?prettyPrint=false: Access Denied: Project quick-keel-213611: User does not have bigquery.jobs.create permission in project quick-keel-213611.

(job ID: airflow_1663528715967019_06d2bf8b43be9b79a3e89edf3b53e367)

             -----Query Job SQL Follows-----             

    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:           select id from githubarchive.day.20220914
   3:        
    |    .    |    .    |    .    |    .    |    .    |

(job ID: airflow_1663528715967019_06d2bf8b43be9b79a3e89edf3b53e367)

             -----Query Job SQL Follows-----             

    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:           select id from githubarchive.day.20220914
   3:        
    |    .    |    .    |    .    |    .    |    .    |
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/sql.py", line 88, in execute
    records = self.get_db_hook().get_first(self.sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 152, in get_first
    cur.execute(sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2639, in execute
    self.job_id = self.hook.run_query(sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2186, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1512, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1159, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/base.py", line 628, in result
    self._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1069, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/base.py", line 438, in _begin
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 640, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/_http.py", line 483, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/quick-keel-213611/jobs?prettyPrint=false: Access Denied: Project quick-keel-213611: User does not have bigquery.jobs.create permission in project quick-keel-213611.

(job ID: airflow_1663528715967019_06d2bf8b43be9b79a3e89edf3b53e367)

             -----Query Job SQL Follows-----             

    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:           select id from githubarchive.day.20220914
   3:        
    |    .    |    .    |    .    |    .    |    .    |

(job ID: airflow_1663528715967019_06d2bf8b43be9b79a3e89edf3b53e367)

             -----Query Job SQL Follows-----             

    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:           select id from githubarchive.day.20220914
   3:        
    |    .    |    .    |    .    |    .    |    .    |
[2022-09-18 19:18:36,483] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=bigquery_dag, task_id=check_query_big_query_table, execution_date=20220910T030000, start_date=20220918T191834, end_date=20220918T191836
[2022-09-18 19:18:36,618] {local_task_job.py:118} INFO - Task exited with return code 1
[2022-09-18 19:40:38,219] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-18 19:40:38,263] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-18 19:40:38,265] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 19:40:38,266] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-09-18 19:40:38,268] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 19:40:38,304] {taskinstance.py:1038} INFO - Executing <Task(BigQueryCheckOperator): check_query_big_query_table> on 2022-09-10T03:00:00+00:00
[2022-09-18 19:40:38,314] {standard_task_runner.py:51} INFO - Started process 3282 to run task
[2022-09-18 19:40:38,338] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery_dag', 'check_query_big_query_table', '2022-09-10T03:00:00+00:00', '--job-id', '423', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bigquery.py', '--cfg-path', '/tmp/tmpsb2lw5zd']
[2022-09-18 19:40:38,346] {standard_task_runner.py:76} INFO - Job 423: Subtask check_query_big_query_table
[2022-09-18 19:40:38,475] {logging_mixin.py:103} INFO - Running <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-10T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-18 19:40:38,596] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=bigquery_dag
AIRFLOW_CTX_TASK_ID=check_query_big_query_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T03:00:00+00:00
[2022-09-18 19:40:38,605] {sql.py:87} INFO - Executing SQL check: 
           select id from githubarchive.day.20220914
        
[2022-09-18 19:40:38,663] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:120 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2022-09-18 19:40:39,397] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:2052 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2022-09-18 19:40:39,402] {bigquery.py:1510} INFO - Inserting job airflow_1663530039400230_06d2bf8b43be9b79a3e89edf3b53e367
[2022-09-18 19:40:58,154] {sql.py:90} INFO - Record: ['23990728531']
[2022-09-18 19:40:58,170] {sql.py:96} INFO - Success.
[2022-09-18 19:40:58,267] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=bigquery_dag, task_id=check_query_big_query_table, execution_date=20220910T030000, start_date=20220918T194038, end_date=20220918T194058
[2022-09-18 19:40:59,052] {local_task_job.py:170} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-09-18 19:40:59,085] {taskinstance.py:1195} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2022-09-18 19:40:59,104] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 3282
[2022-09-18 19:40:59,107] {taskinstance.py:1214} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-09-18 19:40:59,486] {process_utils.py:61} INFO - Process psutil.Process(pid=3282, status='terminated', exitcode=1, started='19:40:37') (3282) terminated with exit code 1
[2022-09-18 19:40:59,500] {local_task_job.py:118} INFO - Task exited with return code 1
