[2022-09-19 13:38:55,121] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-18T03:00:00+00:00 [queued]>
[2022-09-19 13:38:56,119] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-18T03:00:00+00:00 [queued]>
[2022-09-19 13:38:56,203] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 13:38:56,236] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-19 13:38:56,343] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 13:38:58,609] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-18T03:00:00+00:00
[2022-09-19 13:39:07,843] {standard_task_runner.py:51} INFO - Started process 36187 to run task
[2022-09-19 13:39:11,298] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-18T03:00:00+00:00', '--job-id', '509', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpzf_h6j4h']
[2022-09-19 13:39:12,210] {standard_task_runner.py:76} INFO - Job 509: Subtask create_employee_table
[2022-09-19 13:39:36,983] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-18T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-19 13:39:48,441] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-18T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-18T03:00:00+00:00
[2022-09-19 13:39:49,199] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar,
                primary key (emp_id)
            )
        
[2022-09-19 13:40:01,593] {base.py:74} INFO - Using connection to: id: local_postgres. Host: host.docker.internal, Port: 5432, Schema: student, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-19 13:40:10,111] {dbapi.py:180} INFO - Running statement: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar,
                primary key (emp_id)
            )
        , parameters: None
[2022-09-19 13:40:11,110] {dbapi.py:186} INFO - Rows affected: -1
[2022-09-19 13:40:11,569] {postgres.py:73} INFO - NOTICE:  relation "employee" already exists, skipping

[2022-09-19 13:40:16,909] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220918T030000, start_date=20220919T133855, end_date=20220919T134016
[2022-09-19 13:40:24,376] {local_task_job.py:170} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-09-19 13:40:28,032] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-09-19 13:40:28,398] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 36187
[2022-09-19 13:40:33,471] {process_utils.py:61} INFO - Process psutil.Process(pid=36187, status='terminated', exitcode=0, started='13:39:06') (36187) terminated with exit code 0
[2022-09-19 13:40:34,036] {local_task_job.py:118} INFO - Task exited with return code 0
