[2022-09-19 13:40:34,841] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: first_py_dag.python_task_2 2022-09-18T03:00:00+00:00 [queued]>
[2022-09-19 13:40:36,866] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: first_py_dag.python_task_2 2022-09-18T03:00:00+00:00 [queued]>
[2022-09-19 13:40:36,979] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 13:40:37,023] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-19 13:40:37,344] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 13:40:40,398] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): python_task_2> on 2022-09-18T03:00:00+00:00
[2022-09-19 13:40:41,445] {standard_task_runner.py:51} INFO - Started process 36195 to run task
[2022-09-19 13:40:42,928] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'first_py_dag', 'python_task_2', '2022-09-18T03:00:00+00:00', '--job-id', '511', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_operator.py', '--cfg-path', '/tmp/tmpl3q8pr91']
[2022-09-19 13:40:43,094] {standard_task_runner.py:76} INFO - Job 511: Subtask python_task_2
[2022-09-19 13:40:46,988] {logging_mixin.py:103} INFO - Running <TaskInstance: first_py_dag.python_task_2 2022-09-18T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-19 13:40:49,452] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=first_py_dag
AIRFLOW_CTX_TASK_ID=python_task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-09-18T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-18T03:00:00+00:00
[2022-09-19 13:40:50,268] {python.py:118} INFO - Done. Returned value was: None
[2022-09-19 13:40:50,733] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=first_py_dag, task_id=python_task_2, execution_date=20220918T030000, start_date=20220919T134035, end_date=20220919T134050
[2022-09-19 13:40:52,929] {local_task_job.py:170} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-09-19 13:40:53,051] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 36195
[2022-09-19 13:40:53,080] {taskinstance.py:1214} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-09-19 13:40:53,331] {process_utils.py:61} INFO - Process psutil.Process(pid=36195, status='terminated', exitcode=1, started='13:40:41') (36195) terminated with exit code 1
[2022-09-19 13:40:53,648] {local_task_job.py:118} INFO - Task exited with return code 1
